import random
from typing import Dict, List, Any

random.seed(2026189)

def generate_synthetic_dataset() -> Dict[str, Any]:
    # 1. FIVE DISTINCT PRIMARY PERSON PROFILES + 1 AMBIGUOUS CANDIDATE
    profiles = {
        "P-001": {
            "id": "P-001",
            "name": "Arjun Sharma",
            "alias": "Arjun S.",
            "role": "Primary Subject",
            "relationship_to_primary": "Self",
            "age": 34,
            "gender": "Male",
            "photo_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
            "phone": "+91 98765 1201",
            "email": "arjun.sharma.demo@example.test",
            "address": "Flat 402, Shivajinagar",
            "city": "Pune",
            "occupation": "Logistics Consultant",
            "organization": "Nexus Logistics",
            "vehicle": "MH12 AB 4821",
            "social_usernames": {"twitter": "@arjun_s_demo", "telegram": "@cipher_king"},
            "wallet_address": "0xDEMO...A721",
            "account_number": "XXXX4821",
            "notes": "Primary subject under investigation for Operation Nexus.",
            "risk_score": 92,
            "evidence_count": 24,
            "relationship_count": 7,
            "status": "Under Investigation",
            "last_updated": "18 Aug 2026 21:17",
            "counts": {"total_events": 421, "calls": 187, "messages": 234, "contacts": 11, "financial": 63, "osint": 42, "blockchain": 18, "cctv": 3}
        },
        "P-002": {
            "id": "P-002",
            "name": "Rohan Mehta",
            "alias": "Rohan M.",
            "role": "Business Contact",
            "relationship_to_primary": "Business Contact",
            "age": 38,
            "gender": "Male",
            "photo_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
            "phone": "+91 97765 4826",
            "email": "rohan.mehta.demo@example.test",
            "address": "Andheri West, Mumbai",
            "city": "Mumbai",
            "occupation": "Import & Distribution Consultant",
            "organization": "Mehta Global Imports",
            "vehicle": "MH01 CR 7814",
            "social_usernames": {"twitter": "@rohan_m_demo", "telegram": "@rohan_import"},
            "wallet_address": "0xDEMO...B492",
            "account_number": "XXXX7312",
            "notes": "Key commercial importer linked to cross-city invoice settlements.",
            "risk_score": 85,
            "evidence_count": 18,
            "relationship_count": 5,
            "status": "Under Investigation",
            "last_updated": "18 Aug 2026 20:58",
            "counts": {"total_events": 167, "calls": 96, "messages": 71, "contacts": 8, "financial": 31, "osint": 17, "blockchain": 11, "cctv": 3}
        },
        "P-003": {
            "id": "P-003",
            "name": "Priya Joshi",
            "alias": "Priya J.",
            "role": "Associate",
            "relationship_to_primary": "Associate",
            "age": 31,
            "gender": "Female",
            "photo_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80",
            "phone": "+91 96765 7315",
            "email": "priya.joshi.demo@example.test",
            "address": "Baner Road, Pune",
            "city": "Pune",
            "occupation": "Accounts Executive",
            "organization": "Nexus Financial Advisory",
            "vehicle": "MH12 DK 2093",
            "social_usernames": {"linkedin": "in/priya-j-demo", "twitter": "@priya_j_demo"},
            "wallet_address": "0xDEMO...C381",
            "account_number": "XXXX6154",
            "notes": "Managed corporate accounts and audit statement reconciliation.",
            "risk_score": 78,
            "evidence_count": 14,
            "relationship_count": 4,
            "status": "Associate",
            "last_updated": "18 Aug 2026 15:20",
            "counts": {"total_events": 193, "calls": 74, "messages": 119, "contacts": 9, "financial": 18, "osint": 23, "blockchain": 4, "cctv": 3}
        },
        "P-004": {
            "id": "P-004",
            "name": "Vikram Patil",
            "alias": "Vicky",
            "role": "Person of Interest",
            "relationship_to_primary": "Person of Interest",
            "age": 41,
            "gender": "Male",
            "photo_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80",
            "phone": "+91 95765 6148",
            "email": "vikram.patil.demo@example.test",
            "address": "Gangapur Road, Nashik",
            "city": "Nashik",
            "occupation": "Transport Contractor",
            "organization": "Patil Heavy Freight",
            "vehicle": "MH15 TG 4428",
            "social_usernames": {"telegram": "@vikram_p_demo"},
            "wallet_address": "0xDEMO...D527",
            "account_number": "XXXX9087",
            "notes": "Monitored for vehicle fleet movements along the Western Corridor.",
            "risk_score": 72,
            "evidence_count": 11,
            "relationship_count": 3,
            "status": "Person of Interest",
            "last_updated": "18 Aug 2026 20:26",
            "counts": {"total_events": 101, "calls": 58, "messages": 43, "contacts": 6, "financial": 27, "osint": 12, "blockchain": 8, "cctv": 3}
        },
        "P-005": {
            "id": "P-005",
            "name": "Neha Kulkarni",
            "alias": "NK",
            "role": "Employee",
            "relationship_to_primary": "Employee",
            "age": 29,
            "gender": "Female",
            "photo_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80",
            "phone": "+91 94765 3852",
            "email": "neha.kulkarni.demo@example.test",
            "address": "Viman Nagar, Pune",
            "city": "Pune",
            "occupation": "Operations Coordinator",
            "organization": "TechDesk Systems",
            "vehicle": "MH12 EQ 9136",
            "social_usernames": {"twitter": "@neha_k_demo"},
            "wallet_address": "0xDEMO...E614",
            "account_number": "XXXX3246",
            "notes": "Coordinated office dispatch and VPN network gateway routing.",
            "risk_score": 58,
            "evidence_count": 8,
            "relationship_count": 2,
            "status": "Employee",
            "last_updated": "18 Aug 2026 11:00",
            "counts": {"total_events": 130, "calls": 42, "messages": 88, "contacts": 7, "financial": 11, "osint": 19, "blockchain": 2, "cctv": 3}
        },
        "P-006": {
            "id": "P-006",
            "name": "Arjun S.",
            "alias": "Arjun S (Unresolved)",
            "role": "Ambiguous Match Candidate",
            "relationship_to_primary": "Candidate Match",
            "age": 35,
            "gender": "Male",
            "photo_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
            "phone": "+91 98765 9999",
            "email": "arjun.s.ambiguous@example.test",
            "address": "Camp Area, Pune",
            "city": "Pune",
            "occupation": "Commodity Trader",
            "organization": "Unregistered Trading Firm",
            "vehicle": "MH12 AB 9999",
            "social_usernames": {"twitter": "@arjun_s_trader"},
            "wallet_address": "0xDEMO...F000",
            "account_number": "XXXX9999",
            "notes": "POTENTIAL MATCH (Confidence 43%). Signals: Name similarity, Location overlap. Status: Unresolved Candidate.",
            "risk_score": 43,
            "evidence_count": 2,
            "relationship_count": 1,
            "status": "Unresolved Candidate",
            "last_updated": "18 Aug 2026 09:00",
            "counts": {"total_events": 12, "calls": 5, "messages": 7, "contacts": 2, "financial": 3, "osint": 4, "blockchain": 1, "cctv": 1}
        }
    }

    # 2. PERSON-SCOPED CCTV SURVEILLANCE EVENTS (REQUIREMENTS 4, 5, 7, 8, 15, 16)
    cctv_events = {
        "P-001": [
            {
                "id": "EV-CCTV-031",
                "personId": "P-001",
                "camera_id": "CAM-04",
                "camera_name": "CAM-04 (Pune Central Zone)",
                "location": "Shivajinagar, Pune",
                "timestamp": "18 Aug 2026 20:01:00",
                "event_title": "Person Meeting",
                "suspects_identified": ["Arjun Sharma", "Rohan Mehta"],
                "associated_vehicle": "MH12 AB 4821",
                "evidence_id": "EV-CCTV-031",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-04 captured outdoor surveillance frame showing Arjun Sharma meeting Rohan Mehta.",
                "linked_evidence": ["EV-COM-023", "EV-REL-014", "EV-LOC-061"],
                "comm_ref": "COM-ARJ-001",
                "fin_ref": "TXN-88421"
            },
            {
                "id": "EV-CCTV-032",
                "personId": "P-001",
                "camera_id": "CAM-04",
                "camera_name": "CAM-04 (Pune Central Zone)",
                "location": "Shivajinagar, Pune",
                "timestamp": "18 Aug 2026 20:17:38",
                "event_title": "Financial Exchange Event",
                "suspects_identified": ["Arjun Sharma", "Rohan Mehta"],
                "associated_vehicle": "MH12 AB 4821",
                "evidence_id": "EV-CCTV-032",
                "status": "UNDER REVIEW",
                "video_thumbnail": "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-04 captured physical exchange of envelope between subjects at 20:17:38 IST.",
                "linked_evidence": ["EV-FIN-014", "EV-COM-023"],
                "comm_ref": "COM-ARJ-002",
                "fin_ref": "TXN-88421"
            },
            {
                "id": "EV-CCTV-033",
                "personId": "P-001",
                "camera_id": "CAM-04",
                "camera_name": "CAM-04 (Pune Central Zone)",
                "location": "Shivajinagar, Pune",
                "timestamp": "18 Aug 2026 20:26:11",
                "event_title": "Vehicle Departure",
                "suspects_identified": ["Arjun Sharma", "Vikram Patil"],
                "associated_vehicle": "MH12 AB 4821",
                "evidence_id": "EV-CCTV-033",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                "description": "ANPR capture of black SUV MH12 AB 4821 departing meeting location.",
                "linked_evidence": ["EV-LOC-061", "EV-REL-031"],
                "comm_ref": "COM-VIK-001",
                "fin_ref": "TXN-88423"
            }
        ],
        "P-002": [
            {
                "id": "EV-CCTV-ROH-001",
                "personId": "P-002",
                "camera_id": "CAM-08",
                "camera_name": "CAM-08 (Mumbai Port Dock B)",
                "location": "Andheri West, Mumbai",
                "timestamp": "18 Aug 2026 17:40:00",
                "event_title": "Cargo Inspection Sighting",
                "suspects_identified": ["Rohan Mehta"],
                "associated_vehicle": "MH01 CR 7814",
                "evidence_id": "EV-CCTV-ROH-001",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-08 captured Rohan Mehta inspecting commercial freight container.",
                "linked_evidence": ["EV-OSINT-ROH-001", "EV-FIN-ROH-001"],
                "comm_ref": "COM-ROH-001",
                "fin_ref": "TXN-99102"
            },
            {
                "id": "EV-CCTV-ROH-002",
                "personId": "P-002",
                "camera_id": "CAM-04",
                "camera_name": "CAM-04 (Pune Central Zone)",
                "location": "Shivajinagar, Pune",
                "timestamp": "18 Aug 2026 20:01:00",
                "event_title": "Person Meeting",
                "suspects_identified": ["Rohan Mehta", "Arjun Sharma"],
                "associated_vehicle": "MH01 CR 7814",
                "evidence_id": "EV-CCTV-031",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-04 surveillance sighting of Rohan Mehta meeting Arjun Sharma.",
                "linked_evidence": ["EV-COM-ROH-001", "EV-REL-014"],
                "comm_ref": "COM-ROH-001",
                "fin_ref": "TXN-88421"
            },
            {
                "id": "EV-CCTV-ROH-003",
                "personId": "P-002",
                "camera_id": "CAM-08",
                "camera_name": "CAM-08 (Mumbai Port Dock B)",
                "location": "Andheri West, Mumbai",
                "timestamp": "18 Aug 2026 21:10:00",
                "event_title": "Vehicle Arrival",
                "suspects_identified": ["Rohan Mehta"],
                "associated_vehicle": "MH01 CR 7814",
                "evidence_id": "EV-CCTV-ROH-003",
                "status": "UNDER REVIEW",
                "video_thumbnail": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                "description": "ANPR log of MH01 CR 7814 returning to Mumbai facility.",
                "linked_evidence": ["EV-LOC-ROH-001"],
                "comm_ref": "COM-ROH-002",
                "fin_ref": "TXN-99102"
            }
        ],
        "P-003": [
            {
                "id": "EV-CCTV-PRI-001",
                "personId": "P-003",
                "camera_id": "CAM-02",
                "camera_name": "CAM-02 (Baner Financial Hub)",
                "location": "Baner Road, Pune",
                "timestamp": "18 Aug 2026 15:15:00",
                "event_title": "Office Entry",
                "suspects_identified": ["Priya Joshi"],
                "associated_vehicle": "MH12 DK 2093",
                "evidence_id": "EV-CCTV-PRI-001",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-02 security card scan log for Priya Joshi.",
                "linked_evidence": ["EV-FIN-PRI-001", "EV-DOC-057"],
                "comm_ref": "COM-PRI-001",
                "fin_ref": "TXN-77301"
            },
            {
                "id": "EV-CCTV-PRI-002",
                "personId": "P-003",
                "camera_id": "CAM-02",
                "camera_name": "CAM-02 (Baner Financial Hub)",
                "location": "Baner Road, Pune",
                "timestamp": "18 Aug 2026 16:40:00",
                "event_title": "Document Transfer Sighting",
                "suspects_identified": ["Priya Joshi"],
                "associated_vehicle": "MH12 DK 2093",
                "evidence_id": "EV-CCTV-PRI-002",
                "status": "UNDER REVIEW",
                "video_thumbnail": "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-02 corridor capture showing file handoff.",
                "linked_evidence": ["EV-DOC-057"],
                "comm_ref": "COM-PRI-002",
                "fin_ref": "TXN-77301"
            },
            {
                "id": "EV-CCTV-PRI-003",
                "personId": "P-003",
                "camera_id": "CAM-02",
                "camera_name": "CAM-02 (Baner Financial Hub)",
                "location": "Baner Road, Pune",
                "timestamp": "18 Aug 2026 18:00:00",
                "event_title": "Vehicle Departure",
                "suspects_identified": ["Priya Joshi"],
                "associated_vehicle": "MH12 DK 2093",
                "evidence_id": "EV-CCTV-PRI-003",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                "description": "ANPR capture of MH12 DK 2093 leaving Baner parking garage.",
                "linked_evidence": ["EV-LOC-PRI-001"],
                "comm_ref": "COM-PRI-001",
                "fin_ref": "TXN-77301"
            }
        ],
        "P-004": [
            {
                "id": "EV-CCTV-VIK-001",
                "personId": "P-004",
                "camera_id": "CAM-12",
                "camera_name": "CAM-12 (Highway Toll Plaza)",
                "location": "Gangapur Road, Nashik",
                "timestamp": "18 Aug 2026 18:10:00",
                "event_title": "Vehicle Toll ANPR Capture",
                "suspects_identified": ["Vikram Patil"],
                "associated_vehicle": "MH15 TG 4428",
                "evidence_id": "EV-CCTV-VIK-001",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                "description": "ANPR sighting of truck MH15 TG 4428 passing toll plaza.",
                "linked_evidence": ["EV-FIN-VIK-001"],
                "comm_ref": "COM-VIK-002",
                "fin_ref": "TXN-88423"
            },
            {
                "id": "EV-CCTV-VIK-002",
                "personId": "P-004",
                "camera_id": "CAM-04",
                "camera_name": "CAM-04 (Pune Central Zone)",
                "location": "Shivajinagar, Pune",
                "timestamp": "18 Aug 2026 20:26:11",
                "event_title": "Vehicle Departure",
                "suspects_identified": ["Vikram Patil", "Arjun Sharma"],
                "associated_vehicle": "MH12 AB 4821",
                "evidence_id": "EV-CCTV-033",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-04 capture of SUV driven by Vikram Patil.",
                "linked_evidence": ["EV-LOC-061"],
                "comm_ref": "COM-VIK-001",
                "fin_ref": "TXN-88423"
            },
            {
                "id": "EV-CCTV-VIK-003",
                "personId": "P-004",
                "camera_id": "CAM-12",
                "camera_name": "CAM-12 (Highway Toll Plaza)",
                "location": "Gangapur Road, Nashik",
                "timestamp": "18 Aug 2026 22:15:00",
                "event_title": "Freight Yard Arrival",
                "suspects_identified": ["Vikram Patil"],
                "associated_vehicle": "MH15 TG 4428",
                "evidence_id": "EV-CCTV-VIK-003",
                "status": "UNDER REVIEW",
                "video_thumbnail": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-12 capture of truck returning to Nashik freight hub.",
                "linked_evidence": ["EV-LOC-VIK-001"],
                "comm_ref": "COM-VIK-002",
                "fin_ref": "TXN-88423"
            }
        ],
        "P-005": [
            {
                "id": "EV-CCTV-NEH-001",
                "personId": "P-005",
                "camera_id": "CAM-01",
                "camera_name": "CAM-01 (TechDesk Gate 1)",
                "location": "Viman Nagar, Pune",
                "timestamp": "18 Aug 2026 10:55:00",
                "event_title": "Office Entry",
                "suspects_identified": ["Neha Kulkarni"],
                "associated_vehicle": "MH12 EQ 9136",
                "evidence_id": "EV-CCTV-NEH-001",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-01 badge security scan log for Neha Kulkarni.",
                "linked_evidence": ["EV-OSINT-NEH-001"],
                "comm_ref": "COM-NEH-001",
                "fin_ref": "TXN-55104"
            },
            {
                "id": "EV-CCTV-NEH-002",
                "personId": "P-005",
                "camera_id": "CAM-01",
                "camera_name": "CAM-01 (TechDesk Gate 1)",
                "location": "Viman Nagar, Pune",
                "timestamp": "18 Aug 2026 11:15:20",
                "event_title": "Vehicle Arrival",
                "suspects_identified": ["Neha Kulkarni"],
                "associated_vehicle": "MH12 EQ 9136",
                "evidence_id": "EV-CCTV-NEH-002",
                "status": "VERIFIED",
                "video_thumbnail": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                "description": "ANPR log of MH12 EQ 9136 entering staff parking.",
                "linked_evidence": ["EV-LOC-NEH-001"],
                "comm_ref": "COM-NEH-001",
                "fin_ref": "TXN-55104"
            },
            {
                "id": "EV-CCTV-NEH-003",
                "personId": "P-005",
                "camera_id": "CAM-03",
                "camera_name": "CAM-03 (Server Room Corridor)",
                "location": "Viman Nagar, Pune",
                "timestamp": "18 Aug 2026 14:04:18",
                "event_title": "Office Corridor Event",
                "suspects_identified": ["Neha Kulkarni"],
                "associated_vehicle": "MH12 EQ 9136",
                "evidence_id": "EV-CCTV-NEH-003",
                "status": "UNDER REVIEW",
                "video_thumbnail": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-03 keycard log entry into server access zone.",
                "linked_evidence": ["EV-OSINT-NEH-001"],
                "comm_ref": "COM-NEH-001",
                "fin_ref": "TXN-55104"
            }
        ],
        "P-006": [
            {
                "id": "EV-CCTV-AMB-001",
                "personId": "P-006",
                "camera_id": "CAM-09",
                "camera_name": "CAM-09 (Commodity Market Desk)",
                "location": "Camp Area, Pune",
                "timestamp": "18 Aug 2026 09:00:00",
                "event_title": "Market Desk Sighting",
                "suspects_identified": ["Arjun S."],
                "associated_vehicle": "MH12 AB 9999",
                "evidence_id": "EV-CCTV-AMB-001",
                "status": "UNRESOLVED",
                "video_thumbnail": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
                "description": "CAM-09 sighting of ambiguous candidate Arjun S. (Confidence 43%).",
                "linked_evidence": ["EV-OSINT-AMB-001"],
                "comm_ref": "COM-AMB-001",
                "fin_ref": "TXN-11001"
            }
        ]
    }

    # CAMERA LOCATIONS STRIP (REQUIREMENTS 9 & 18)
    camera_locations = [
        {"camera_id": "CAM-04", "location": "Pune Central Zone", "status": "Active Recording", "date": "18 Aug 2026"},
        {"camera_id": "CAM-01", "location": "TechDesk Gate 1", "status": "Active Recording", "date": "18 Aug 2026"},
        {"camera_id": "CAM-02", "location": "Baner Financial Hub", "status": "Active Recording", "date": "18 Aug 2026"},
        {"camera_id": "CAM-08", "location": "Mumbai Port Dock B", "status": "Archived", "date": "18 Aug 2026"},
        {"camera_id": "CAM-12", "location": "Highway Toll Plaza", "status": "Active Recording", "date": "18 Aug 2026"},
        {"camera_id": "CAM-03", "location": "Server Room Corridor", "status": "Active Recording", "date": "18 Aug 2026"}
    ]

    # Return complete dataset
    return {
        "profiles": profiles,
        "cctv": cctv_events,
        "camera_locations": camera_locations,
        "cases": {
            "TRX-2026-017": {
                "id": "TRX-2026-017",
                "title": "OPERATION NEXUS",
                "primary_suspect": profiles["P-001"],
                "secondary_suspects": [profiles["P-002"], profiles["P-003"], profiles["P-004"], profiles["P-005"]]
            }
        }
    }
