import time
from typing import Dict, List, Any

class ReportGenerator:
    def __init__(self):
        pass

    def generate_report(
        self,
        case_data: Dict[str, Any],
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
        evidence_items: List[Dict[str, Any]],
        fusion_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        
        timestamp_str = time.strftime("%Y-%m-%d %H:%M:%S IST")
        
        primary_name = "Arjun Sharma"
        if "primary_suspect" in case_data and isinstance(case_data["primary_suspect"], dict):
            primary_name = case_data["primary_suspect"].get("name", "Arjun Sharma")
        elif "subject_name" in case_data:
            primary_name = case_data["subject_name"]

        case_id = case_data.get("id", "TRX-2026-017")
        case_title = case_data.get("title", "Operation Nexus")
        status = case_data.get("status", "Active Investigation")
        priority = case_data.get("priority", "High")
        lead = case_data.get("lead_investigator", "Ins. Vikramaditya Rao (#INV-7092)")

        explainable_ai = fusion_data.get('explainable_ai', {}) if isinstance(fusion_data, dict) else {}
        what_str = explainable_ai.get('WHAT', 'Multi-hop chain correlated across CDR, DVR, and Financial logs.')
        why_str = explainable_ai.get('WHY', 'Repeated temporal burst and account transfer correlation.')

        evd_rows = ""
        for e in evidence_items[:8]:
            eid = e.get('id', '')
            etype = e.get('evidence_type', '')
            etitle = e.get('title', '')
            esrc = e.get('source', '')
            ehash = e.get('file_hash', '')[:14]
            evd_rows += f"<tr><td><strong>{eid}</strong></td><td>{etype}</td><td>{etitle}</td><td>{esrc}</td><td><span class='badge'>{ehash}...</span></td></tr>"

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>TRACE-X Official Investigation Dossier - {case_id}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #0f172a; padding: 24px; line-height: 1.5; font-size: 13px; }}
        h1, h2, h3 {{ color: #1e3a8a; font-weight: 800; border-bottom: 2px solid #2563eb; padding-bottom: 4px; }}
        .meta-table, .data-table {{ width: 100%; border-collapse: collapse; margin-bottom: 16px; }}
        .meta-table th, .meta-table td, .data-table th, .data-table td {{ padding: 8px 12px; border: 1px solid #cbd5e1; text-align: left; }}
        .meta-table th, .data-table th {{ background-color: #f1f5f9; color: #334155; font-weight: 800; text-transform: uppercase; font-size: 11px; }}
        .badge {{ background-color: #eff6ff; color: #2563eb; padding: 2px 6px; border-radius: 4px; font-weight: 700; font-size: 10px; }}
        .disclaimer {{ background-color: #fffbeb; border: 1px solid #fde68a; padding: 12px; border-radius: 6px; font-size: 11px; margin-bottom: 20px; }}
    </style>
</head>
<body>

    <div style="display: flex; justify-content: space-between; align-items: center;">
        <div>
            <h1 style="margin:0;">TRACE-X OFFICIAL INVESTIGATION REPORT</h1>
            <div style="font-size: 11px; color: #64748b;">CONFIDENTIAL // SIH26189 CRIMINAL NETWORK ANALYSIS SYSTEM</div>
        </div>
        <div style="text-align: right; font-size: 11px; color: #64748b;">
            <div>Generated: {timestamp_str}</div>
            <div>Dossier Ref: {case_id}-DOSSIER</div>
        </div>
    </div>

    <hr style="margin: 16px 0; border: none; border-top: 1px solid #cbd5e1;">

    <div class="disclaimer">
        <strong>⚖️ LEGAL NOTICE & COMPLIANCE STATEMENT:</strong><br>
        This dossier is generated by the TRACE-X AI Evidence Fusion Workstation under SIH26189. All investigative leads are analytical decision support findings and require manual human verification under Sec 91 & Sec 65B of the Indian Evidence Act.
    </div>

    <h2>1. Executive Summary</h2>
    <table class="meta-table">
        <tr><th>Case Reference</th><td>{case_id}</td><th>Case Title</th><td>{case_title}</td></tr>
        <tr><th>Primary Subject</th><td><strong>{primary_name}</strong></td><th>Status</th><td><span class="badge">{status}</span></td></tr>
        <tr><th>Priority</th><td>{priority}</td><th>Lead Investigator</th><td>{lead}</td></tr>
        <tr><th>Jurisdiction</th><td>Pune, Maharashtra</td><th>Agency</th><td>Special Cyber Crime Cell</td></tr>
    </table>

    <h2>2. Key Evidence & Correlated Entities</h2>
    <table class="data-table">
        <thead>
            <tr><th>Evidence ID</th><th>Type</th><th>Title</th><th>Source</th><th>Hash Verification</th></tr>
        </thead>
        <tbody>
            {evd_rows}
        </tbody>
    </table>

    <h2>3. AI Evidence Fusion Findings</h2>
    <p><strong>Primary Multi-Hop Chain:</strong> {what_str}</p>
    <p><strong>Flagging Rationale:</strong> {why_str}</p>

    <h2>4. Investigator Sign-Off</h2>
    <div style="margin-top: 40px; display: flex; justify-content: space-between;">
        <div>
            <div>__________________________________</div>
            <div><strong>Ins. Vikramaditya Rao (#INV-7092)</strong></div>
            <div>Lead Investigator, SCCIC</div>
        </div>
        <div>
            <div>__________________________________</div>
            <div><strong>Superintendent of Police</strong></div>
            <div>Cyber Crime Division</div>
        </div>
    </div>

</body>
</html>"""

        return {
            "case_id": case_id,
            "generated_at": timestamp_str,
            "html_content": html_content
        }

report_generator = ReportGenerator()
